# bot settings
bot_token: "2030095981:AAH4QhW1ZQM9GNWgvqlgqPbfCIpsCb6yBhA" # support bot tok                                                                                                             en
staffchat_id: "-556874304" # eg. -123456789
owner_id: "479705557"
spam_time: 5 * 60 * 1000 # time (in MS) in which user may send 5 messages

allow_private: false # Allow / disallow option for staff to chat privately
direct_reply: false # Set this to true to just forward staff users to a user chat when allow_private

auto_close_tickets: true # Close tickets after answering
anonymous_tickets: true # Include userid in tickets or not

signal_enabled: false # Enable/disable signal
signal_number: '+12345689' # Your signal number / account

web_server: false # Enable/disable web server
web_server_port: 8080 # Port for web server
web_server_ssl_cert: '../src/web/ssl.crt' # Path for SSL cert
web_server_ssl_key: '../src/web/ssl.key' # Path for SSL key

dev_mode: true # Enable/disable dev mode

# customize your language
language:
    startCommandText: "Вітаємо в нашому чаті підтримки. Задайте своє запитання."
    faqCommandText: "Підтримка: <a href='https://github.com/bostrot/telegram-support-bot'>github.com</a>"
    helpCommandText: "<b>Доступні команди:</b>\n/help\n/faq\n/id"
    contactMessage: "Дякуємо, що зв’язалися з нами. Ми відповімо якомога швидше.\n"
    blockedSpam: "За останній час ви надіслали чимало запитань. Будь ласка, заспокойтеся і почекайте, поки персонал їх перевірить."
    ticket: "Звернення"
    closed: "закрито"
    acceptedBy: "був прийнятий"
    dear: "Дорогий(-а)"
    regards: "З найкращими побажаннями,"
    from: "від"
    language: "Мова"
    msg_sent: "Повідомлення відправлене користувачу"
    file_sent: "Файл відправлений користувачу"
    usr_with_ticket: "Користувач зі зверненням"
    banned: "бан"
    replyPrivate: "Відповідь в приватні повідомлення"
    services: "Виберіть послугу зі списку нижче"
    customer: "клієнт"
    msgForwarding: "Тепер ваші повідомлення будуть пересилатися постачальникам групи: "
    back: "Назад"
    whatSubCategory: "Яка підкатегорія найкраще описує ваші потреби? "
    prvChatEnded: "Приватний чат закінчився."
    prvChatOpened: "Відкрито приватний чат із клієнтом."
    prvChatEnd: "Завершено приватний чат"
    prvChatOpenedCustomer: "Відкрито приватний чат"
    instructionsSent: "Інструкції були надіслані вам у приватному чаті."
    openTickets: "Відкриті звернення"
    support: "Підтримка"
    prvChatOnly: "Цю команду можна використовувати лише в приватному чаті."
    ticketClosed: "Ваш квиток закрили наші співробітники. Ви можете відкрити новий квиток у будь -який час."
    links: "Прямі посилання на підтримку"
    textFirst: "Будь ласка, надішліть нам повідомлення перед надсиланням зображення, щоб ми могли вам допомогти краще."
    ticketClosedError: "Ви не можете відповісти на закритий квиток."
    automatedReply: "Це автоматична відповідь."
    automatedReplyAuthor: "BottyBot."
    doesntHelp: "Це не допомагає."
    automatedReplySent: "Користувачу надіслано автоматичну відповідь."

# categories: 
#  - name: "Category1"
#    subgroups:
#    - name: "Sub1"
#      group_id: "-12345678910"
#    - name: "Sub2"
#      group_id: "-12345678910"
#    - name: "Sub3"
#      group_id: "-12345678910"
#  - name: "Category2"
#    subgroups: 
#    - name: "Sub4"
#      group_id: "-12345678910"
#    - name: "Sub5"
#      group_id: "-12345678910"
#    - name: "Sub6"
#      group_id: "-12345678910"
#  - name: "Category with no subcategories"
#    group_id: "-12345678910"
#  - name: "Admin Chat"
#    group_id: "-12345678910" 
#  - name: "Contact"
#    msg: "Check out our Website"

    
  
